Exec:
# 0: do not run;
# 1: Continue running:
# For tasks without a checkpoint mechanism, if an output_file exists, it will not run; otherwise, it will.
# For tasks with a checkpoint mechanism, it will continue from the checkpoint.
# 2: Rerun: delete the output_file and run again.

  preprocess:    2 # 
  make_prompt:   2 #1
  generate_code: 2 #2
  postprocess:   2 #2
  eval:          1

  efficiency_stat: 0  
  
ROOT_PATH_GEN: /root/workspace/code/anonymousCodeContext
EXEC_DATA_DIR: /root/workspace/code/RUN/experiment/simple


RUN_LOG_PATH: ${EXEC_DATA_PATH}/run.log

Dataset:
  # DevEval, CoderEval
  name: DevEval
  meta_data: /root/workspace/code/anonymousCodeContext/data/DevEval/data_fixed2_sample_pre_proj.jsonl
  source_code: /root/workspace/code/DevEval/Source_Code2
  id_key: namespace

# gpt, gemini, claude
MODEL: gpt
TASK: navigation_plus
# MODA: sampling
MODA: greedy

EXEC_DATA_TASK_PATH: ${EXEC_DATA_DIR}/${Dataset.name}/${TASK}
EXEC_DATA_PATH: ${EXEC_DATA_TASK_PATH}/${MODEL}/${MODA}

Preprocess:
  # baseline, infilling, similarity
  type: navigation
  output_dir:  ${EXEC_DATA_TASK_PATH}/preprocess/${Preprocess.type}

  baseline:
    output_path: ${EXEC_DATA_TASK_PATH}/preprocess/raw_elements.jsonl
  
  infilling:
    output_path: ${EXEC_DATA_TASK_PATH}/preprocess/raw_elements.jsonl

  similarity:
    method: cocosoda
    train_prompt_elem_path: /root/workspace/code/anonymousCodeContext/data/DevEval/prompt_elements_source_code2.jsonl
    test_meta_data_path: ${Dataset.meta_data}
    output_dir: ${EXEC_DATA_TASK_PATH}/preprocess/similarity
    output_path: ${Preprocess.similarity.output_dir}/indexing_${Preprocess.similarity.method}_${Preprocess.similarity.number}.jsonl
    number: 5
    # output_path: ${EXEC_DATA_TASK_PATH}/preprocess/elements_${Preprocess.similarity.method}_${Preprocess.similarity.N}.jsonl
    # output_path:  /root/workspace/code/anonymousCodeContext/data/DevEval/similarity/test_bm25_10.jsonl

    # for Embeding model only
    train_embedding_path: ${ROOT_PATH_GEN}/data/DevEval/similarity/cocosoda_embeddings_prompt_elements_source_code2.npy
    test_embedding_path: ${ROOT_PATH_GEN}/data/DevEval/similarity/cocosoda_embeddings_prompt_elements_source_code2_sample_per_proj.npy
    re_embedding: false
  
  navigation:
    prompt_elem_file: /root/workspace/code/anonymousCodeContext/data/DevEval/prompt_elements_source_code2_sample_per_proj.jsonl
    meta_data_path: data/DevEval/data_fixed2_sample_pre_proj.jsonl
    run_base_dir: /root/workspace/code/RUN/tmp/agent/generate_prompt/running_env
    source_code_path: /root/workspace/code/DevEval/Source_Code2
    # model: qwen3
    max_iterations: 30
    api_key: your key
    open_key: your key
    min_count: 2
    output_path: /root/workspace/code/RUN/agent_plus_generate_prompt/ckpt/${MODEL}/
    max_concurrent_num: 10

    plus: true


MakePrompt:
  
  type: ${Preprocess.type}
  max_token_length: 50000
  context_window: 128000
  N: 5

  preprocess_file: /root/workspace/code/RUN/agent_generate_prompt/ckpt/${MODEL}/latest.jsonl
  elem_data_path: /root/workspace/code/anonymousCodeContext/data/DevEval/prompt_elements_source_code2.jsonl
  template_path: /root/workspace/code/anonymousCodeContext/prompt/template/navigation_template_refine.txt
  meta_data_path: ${Dataset.meta_data}
  
  output_path: ${EXEC_DATA_PATH}/prompt_${MakePrompt.context_window}_${MakePrompt.max_token_length}_${MakePrompt.N}.jsonl


GenerateCode:
  # agent, baseline, infilling, similarity
  type: agent
  prompt_file: ${MakePrompt.output_path}
  output_dir: ${EXEC_DATA_PATH}/generate_code/
  api_key_file: ${ROOT_PATH_GEN}/llm_key/key1.txt 
  open_key: your key
  max_concurrent: 20
  min_count: ${Preprocess.navigation.min_count}

Postprocess:
  output_file: ${EXEC_DATA_PATH}/postprocess/completion.jsonl


Eval:
  output_file: ${Postprocess.output_file}
  log_file: ${EXEC_DATA_PATH}/eval/test_output.jsonl
  source_code_root: ${Dataset.source_code}
  data_file: ${Dataset.meta_data}
  # n: 5
  # k: 1,3,5
  n: 1
  k: '1'

Stat:
  llm_output_file: ${GenerateCode.output_dir}/latest.jsonl