Exec:
# 0: do not run;
# 1: Continue running:
# For tasks without a checkpoint mechanism, if an output_file exists, it will not run; otherwise, it will.
# For tasks with a checkpoint mechanism, it will continue from the checkpoint.
# 2: Rerun: delete the output_file and run again.

  preprocess:    1 # 
  make_prompt:   1 #1
  generate_code: 1 #2
  postprocess:   1 #2
  eval:          1

  efficiency_stat: 1  
  
ROOT_PATH_GEN: /root/workspace/code/anonymousCodeContext
EXEC_DATA_DIR: /root/workspace/code/RUN/experiment/simple


RUN_LOG_PATH: ${EXEC_DATA_PATH}/run.log

Dataset:
  # DevEval, CoderEval
  name: DevEval
  meta_data: /root/workspace/code/anonymousCodeContext/data/DevEval/data_fixed2_sample_pre_proj.jsonl
  source_code: /root/workspace/code/DevEval/Source_Code2
  id_key: namespace

# gpt, gemini, claude
MODEL: gpt
TASK: sa
# MODA: sampling
MODA: greedy

EXEC_DATA_TASK_PATH: ${EXEC_DATA_DIR}/${Dataset.name}/${TASK}
EXEC_DATA_PATH: ${EXEC_DATA_TASK_PATH}/${MODEL}/${MODA}

Preprocess:
  # baseline, infilling, similarity, sa
  type: sa
  output_dir:  ${EXEC_DATA_TASK_PATH}/preprocess/${Preprocess.type}

  baseline:
    output_path: ${EXEC_DATA_TASK_PATH}/preprocess/raw_elements.jsonl
  
  infilling:
    output_path: ${EXEC_DATA_TASK_PATH}/preprocess/raw_elements.jsonl

  similarity: nothing
    # method: bm25
    # train_prompt_elem_path: /root/workspace/code/anonymousCodeContext/data/DevEval/prompt_elements_source_code2.jsonl
    # test_meta_data_path: ${Dataset.meta_data}
    # output_dir: ${EXEC_DATA_TASK_PATH}/preprocess/similarity
    # number: 5
    # output_path: ${Preprocess.similarity.output_dir}/indexing_${Preprocess.similarity.method}_${Preprocess.similarity.number}.jsonl
    # output_path: ${EXEC_DATA_TASK_PATH}/preprocess/elements_${Preprocess.similarity.method}_${Preprocess.similarity.N}.jsonl
    # output_path:  /root/workspace/code/anonymousCodeContext/data/DevEval/similarity/test_bm25_10.jsonl
  sa:
    output_path: nothing

MakePrompt:
  
  type: ${Preprocess.type}
  max_token_length: 50000
  context_window: 128000
  N: 5

  template_path: /root/workspace/code/anonymousCodeContext/prompt/template/sa_template_refine.txt
  element_path: /root/workspace/code/anonymousCodeContext/data/DevEval/prompt_elements_source_code2.jsonl
  meta_data_path: ${Dataset.meta_data}
  depandancy_dir: /root/workspace/code/anonymousCodeContext/data/DevEval/sa
  output_path: ${EXEC_DATA_TASK_PATH}/prompt_sa.jsonl


GenerateCode:
  # agent, baseline, infilling, similarity
  type: sa
  prompt_file: ${MakePrompt.output_path}
  output_dir: ${EXEC_DATA_PATH}/generate_code/
  api_key_file: ${ROOT_PATH_GEN}/llm_key/key1.txt 
  open_key: your key
  max_concurrent: 20
  min_count: -1

Postprocess:
  output_file: ${EXEC_DATA_PATH}/postprocess/completion.jsonl


Eval:
  output_file: ${Postprocess.output_file}
  log_file: ${EXEC_DATA_PATH}/eval/test_output.jsonl
  source_code_root: ${Dataset.source_code}
  data_file: ${Dataset.meta_data}
  # n: 5
  # k: 1,3,5
  n: 1
  k: '1'

Stat:
  llm_output_file: ${GenerateCode.output_dir}/latest.jsonl