Exec:
  preprocess:    0 # 
  make_prompt:   0 #1
  generate_code: 0 #2
  postprocess:   2 #2
  eval:          0

  efficiency_stat: 1  


ROOT_PATH_GEN: /root/workspace/code/anonymousCodeContext
# EXEC_DATA_DIR: /root/workspace/code/RUN/test_tmp2
EXEC_DATA_DIR: /root/workspace/code/RUN/experiment/


RUN_LOG_PATH: ${EXEC_DATA_PATH}/run.log

Dataset:
  name: CoderEval
  meta_data: /root/workspace/code/anonymousCodeContext/data/CoderEval/metadata.jsonl
  source_code: /root/workspace/code/anonymousCodeContext/data/CoderEval/dummy_source_code
  id_key: namespace
  language: python


# gpt, gemini, claude
MODEL: gpt
TASK: sa
# MODA: sampling
MODA: greedy

EXEC_DATA_TASK_PATH: ${EXEC_DATA_DIR}/${Dataset.name}/${TASK}
EXEC_DATA_PATH: ${EXEC_DATA_TASK_PATH}/${MODEL}/${MODA}

Preprocess:
  # baseline, infilling, similarity
  type: sa
  output_dir:  ${EXEC_DATA_TASK_PATH}/preprocess/${Preprocess.type}

  baseline:
    output_path: ${EXEC_DATA_TASK_PATH}/preprocess/raw_elements.jsonl
  
  infilling:
    output_path: /root/workspace/code/anonymousCodeContext/data/CoderEval/elements.jsonl

  similarity:
    method: sa
    train_prompt_elem_path: /root/workspace/code/anonymousCodeContext/data/CoderEval/elements.jsonl
    test_meta_data_path: ${Dataset.meta_data}
    output_dir: ${EXEC_DATA_TASK_PATH}/preprocess/similarity
    output_path: ${Preprocess.similarity.output_dir}/indexing_${Preprocess.similarity.method}_${Preprocess.similarity.number}.jsonl
    number: 5

    train_embedding_path: ${ROOT_PATH_GEN}/data/CoderEval/similarity/cocosoda_embeddings_prompt_elements_source_code2.npy
    test_embedding_path: ${ROOT_PATH_GEN}/data/CoderEval/similarity/cocosoda_embeddings_prompt_elements_source_code2_sample_per_proj.npy
    re_embedding: false

  sa:
    output_path: nothing

MakePrompt:
  
  type: ${Preprocess.type}
  max_token_length: 50000
  context_window: 128000
  N: 5

  template_path: /root/workspace/code/anonymousCodeContext/prompt/template/sa_template_refine.txt
  element_path: /root/workspace/code/anonymousCodeContext/data/CoderEval/elements.jsonl
  meta_data_path: ${Dataset.meta_data}
  depandancy_dir: /root/workspace/code/anonymousCodeContext/data/CoderEval/sa
  output_path: ${EXEC_DATA_TASK_PATH}/prompt_sa.jsonl


GenerateCode:
  # agent, baseline, infilling, similarity
  type: sa
  prompt_file: ${MakePrompt.output_path}
  output_dir: ${EXEC_DATA_PATH}/generate_code/
  api_key_file: ${ROOT_PATH_GEN}/llm_key/key1.txt 
  open_key: your key
  max_concurrent: 20
  min_count: -1

Postprocess:
  output_file: /root/workspace/code/CoderEval/docker_mount_out_data/python/postprocess/${TASK}/${MODEL}.jsonl


Eval:
  output_file: ${Postprocess.output_file}
  log_file: ${EXEC_DATA_PATH}/eval/test_output.jsonl
  source_code_root: ${Dataset.source_code}
  data_file: ${Dataset.meta_data}
  # n: 5
  # k: 1,3,5
  n: 1
  k: '1'

Stat:
  llm_output_file: ${GenerateCode.output_dir}/latest.jsonl